name: Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "dash-brainhack" #Must be unique in Heroku
          heroku_email: "agahkarakuzu@gmail.com"
          usedocker: true
          docker_heroku_process_type: "web"
